name: build hugo  # 任意の名前をつけます

on:  # トリガーの設定
  push:
    branches:
      - master  # "master" ブランチに push されたときに実行
  pull_request:
    branches:
      - master  # "master" ブランチに対するプルリクエストが作成されたときに実行

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        submodules: true  # サブモジュールを取得する

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'

    - name: Build Hugo Site
      run: hugo --minify

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public